services:	
    koutogima.autosave.event.main_listener:
        class: koutogima\autosave\event\main_listener
        arguments:
            - @user
        tags:
            - { name: event.listener }