services:
    koutogima.allowusertodelete.listener:
        class: koutogima\allowusertodelete\event\listener
        arguments:
            - @user
            - @auth
            - @config
            - @content.visibility
        tags:
            - { name: event.listener }