services:
    ntvy95.dicek.event.main_listener:
        class: ntvy95\dicek\event\main_listener
        arguments:
            - @dbal.conn
            - %tables.posts%
        tags:
            - { name: event.listener }
